server {
    listen 80;  # Listen on port 80
    index index.php index.html;  # Default index files
    error_log  /var/log/nginx/error.log;  # Error log path
    access_log /var/log/nginx/access.log;  # Access log path
    root /var/www/public;  # Web root directory

    # PHP files handling
    location ~ \.php$ {
        try_files $uri =404;  # Return 404 if the file does not exist
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # 'app' here is the name of the service defined in docker-compose.yml
        fastcgi_pass app:9000;  # Forward PHP requests to the PHP-FPM container
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Handle all other requests
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;  # Serve pre-compressed gzip files if available
    }
}